<h2 class="section">Erreur détectée</h2>
<p>Clé de validation invalide.</p>

<p style="color: #FF3333;">Si vous lisez ce message, cela signifie probablement que votre compte est
    <strong>déjà activé</strong> et qu'il suffit de <a href="<?php echo $this->url(array(
        'action' => 'mes-alertes', 'controller' => 'compte', 'module' => 'api'
    ), 'default'); ?>"><strong>vous connecter</strong></a>.</p>
