<div>
	<strong>Publié le <?php echo $this->ad->getDate(Zend_Date::DATETIME_MEDIUM); ?></strong>
    <br />

    <strong>Nom</strong> : <a href="<?php echo $this->ad->getLink(); ?>"><?php echo $this->ad->getTitle(); ?></a>
    <?php if ($this->ad->getPrice()) : ?>
    &nbsp;&nbsp;&nbsp;&nbsp;<strong>Prix</strong> : <?php echo number_format($this->ad->getPrice(), 0, ',', ' '); ?> €
    <?php endif; ?>
    
    <?php if ($this->ad->getCategory()) : ?>
    <br />
    <strong>Catégorie</strong> : <?php echo $this->ad->getCategory(); ?>
    <?php endif; ?>
    <br />
    <?php if ($this->ad->getCounty()) : ?>
    <strong>Département</strong> : <?php echo $this->ad->getCounty(); ?>
    <?php endif; ?>
    <?php if ($this->ad->getCity()) : ?>
    &nbsp;&nbsp;&nbsp;&nbsp;<strong>Ville</strong> : <a href="http://maps.google.fr/?z=9&q=<?php
        echo $this->escape($this->ad->getCounty().' '.$this->ad->getCity());
    ?>" title="Localiser sur Google Map"><?php echo $this->ad->getCity(); ?></a>
    <?php endif; ?>
    <br />Annonce de <?php echo $this->ad->getProfessionnal()?'professionnel':'particulier.'; ?>
    <br />
    <?php if ($this->ad->getUrgent()) : ?>
    <strong style="color: #FF8900;">urgent</strong>
    <?php endif; ?>
    <?php if ($this->ad->getThumbnailLink()) : ?>
    <br /><img src="<?php echo str_replace('/thumbs/', '/images/', $this->ad->getThumbnailLink()); ?>" alt="" />
    <?php else : ?>
    <br />Pas de photo disponible.
    <?php endif; ?>
</div>